### ISSUE TITLE
tkt-maintenance-public.css

### ISSUE THREAD

**Issue by joyously** [TukuToi/tukutoi-maintenance#20]
https://github.com/TukuToi/tkt-maintenance/blob/18c552f0089296be71e39d1c9521a61df0f6d6e1/public/css/tkt-maintenance-public.css#L14

Since you don't know the image color or transparency, and you didn't set the body background color, you probably need to use some text-shadow to make sure the text is visible.

https://github.com/TukuToi/tkt-maintenance/blob/18c552f0089296be71e39d1c9521a61df0f6d6e1/public/css/tkt-maintenance-public.css#L15

I suggest you use `font-family: serif;` or `font-family: sans-serif;` instead so it works for all languages.

https://github.com/TukuToi/tkt-maintenance/blob/18c552f0089296be71e39d1c9521a61df0f6d6e1/public/css/tkt-maintenance-public.css#L16

It would be more accessible with `font-size: 150%`

https://github.com/TukuToi/tkt-maintenance/blob/18c552f0089296be71e39d1c9521a61df0f6d6e1/public/css/tkt-maintenance-public.css#L23-L25

Won't this distort the image?

**Comment by smileBeda** [comment]
1. Excellent catch.
2. Ditto.
3. Ditto.
4. I don't think so, height is fixed, with is auto, thus, as related to image and since they are supposed to add square image, it wont distort. Even if the image is not square, it will simply adapt the width to whatever rationally to height. Check https://www.w3schools.com/cssref/tryit.asp?filename=trycss_dim_width_percent, and change the `img.normal` to a height (fixed). It wont distort the image.

**Comment by joyously** [comment]
>  It wont distort the image.

I forgot that your template doesn't output the width and height attributes. And since you are not using `max-width: 100%` like most themes would, then it's different. But I wouldn't assume that the image is square. The user always does something different.
